CREATE TABLE Employees
(
    Id UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    FirstName NVARCHAR(MAX) NOT NULL,
    LastName NVARCHAR(MAX) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Sex NVARCHAR(6) NOT NULL,
    JobTitle NVARCHAR(MAX) NOT NULL,
    HireDate DATE NOT NULL,
    HomeAddress NVARCHAR(MAX),
    Salary MONEY NOT NULL
)